package recoverytrace

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"sort"
	"testing"
)

// ledgerDir holds the published recovery ledgers. They are checked in so the
// evidence can be read without running Go, which is exactly why CI has to prove
// the checked-in bytes still match what the generator produces.
const ledgerDir = "../../docs/audits/data/organic-rdd-recovery"

// updateLedgers regenerates the published documents instead of asserting them.
// The ledgers are never hand-authored: this flag is the only supported way to
// change them, so a JSON edit can never enter the repository unproduced.
//
//	go test ./internal/recoverytrace/ -run TestGeneratedLedgersAreCurrent -update-ledgers
var updateLedgers = flag.Bool("update-ledgers", false,
	"regenerate the published recovery ledgers instead of asserting they are current")

func declaredDocuments(t *testing.T) map[string][]byte {
	t.Helper()

	documents, err := Render(declaredLedgers(t))
	if err != nil {
		t.Fatalf("Render(declared rows) error = %v", err)
	}
	return documents
}

// TestGeneratedLedgersAreCurrent is the generated-current gate. It fails when a
// published ledger differs from the generator's output by a single byte, which
// is what a hand edit to the JSON looks like from here.
func TestGeneratedLedgersAreCurrent(t *testing.T) {
	documents := declaredDocuments(t)

	if *updateLedgers {
		writeLedgers(t, documents)
		return
	}

	for name, want := range documents {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			path := filepath.Join(ledgerDir, name)
			got, err := os.ReadFile(filepath.Clean(path))
			if err != nil {
				t.Fatalf("read %s: %v; regenerate with -update-ledgers", name, err)
			}
			if !bytes.Equal(got, want) {
				t.Fatalf("%s is not what the generator produces; it was edited by hand "+
					"or the declared rows changed. Regenerate with -update-ledgers.", name)
			}
		})
	}
}

// TestPublishedLedgerDirectoryHasNoStrayDocuments proves the published set is
// exactly the generated set. A leftover ledger from an earlier shape would
// otherwise sit beside the current ones and read as equally authoritative.
func TestPublishedLedgerDirectoryHasNoStrayDocuments(t *testing.T) {
	entries, err := os.ReadDir(filepath.Clean(ledgerDir))
	if err != nil {
		t.Fatalf("read %s: %v", ledgerDir, err)
	}

	published := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		published = append(published, entry.Name())
	}
	sort.Strings(published)

	generated := make([]string, 0, len(entries))
	for name := range declaredDocuments(t) {
		generated = append(generated, name)
	}
	sort.Strings(generated)

	if len(published) != len(generated) {
		t.Fatalf("published %v, generated %v", published, generated)
	}
	for index := range generated {
		if published[index] != generated[index] {
			t.Fatalf("published %v, generated %v", published, generated)
		}
	}
}

// writeLedgers publishes the generated bytes. It writes through the same map the
// assertion reads, so the update path cannot produce something the check would
// then reject.
func writeLedgers(t *testing.T, documents map[string][]byte) {
	t.Helper()

	if err := os.MkdirAll(filepath.Clean(ledgerDir), 0o755); err != nil {
		t.Fatalf("create %s: %v", ledgerDir, err)
	}
	for name, document := range documents {
		path := filepath.Join(ledgerDir, name)
		if err := os.WriteFile(filepath.Clean(path), document, 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(document))
	}
}
